Added cleanup in Workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,6 +48,15 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
 
+
+      - name: Free up disk space
+        run: |
+          echo "Cleaning up space to avoid 'no space left on device' errors..."
+          docker system prune -af
+          docker volume prune -f
+          sudo rm -rf /usr/local/lib/android /opt/hostedtoolcache /usr/share/dotnet /usr/local/share/boost || true
+          df -h
+
       - name: Build, tag, and push image to Amazon ECR
         id: build-image
         env:
